name: navigation_rail
description: A Navigation Rail for Flutter
version: 1.6.0-dev.1
author: Rody Davis <rody.davis.jr@gmail.com>
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/navigation_rail

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
